apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myadmin-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: myadmin-cert
  rules:
    - host: {{ .Values.domainMyAdmin }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myadmin
                port:
                  number: 443
