apiVersion: v2
name: helm-mariadb-operator
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for MariaDB Operator

dependencies:
  - name: mariadb-operator
    version: "0.19.0"
    repository: "https://mariadb-operator.github.io/mariadb-operator"
    condition: mariadb-operator.enabled
