apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmr-audit
  namespace: xmr-audit
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: xmr-audit
  template:
    metadata:
      labels:
        app: xmr-audit
    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: xmr-audit
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
          - name: ADDRESS
            valueFrom:
              secretKeyRef:
                name: xmr-audit-cfg
                key: WALLET_ADDRESS

          - name: WORKER_ID
            valueFrom:
              secretKeyRef:
                name: xmr-audit-cfg
                key: WORKER_ID

        securityContext: {}
