apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xmr-audit-cfg
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: xmr-audit-cfg       # name of the k8s Secret to be created
  data:
  - secretKey: "WALLET_ADDRESS" 
    remoteRef:
      key: initial-secret
      property: WALLET_ADDRESS

  - secretKey: "WORKER_ID"
    remoteRef:
      key: initial-secret
      property: DEVICE_ID
