moodle:
  enabled: true
  fullnameOverride: moodle
  nameOverride: moodle
  replicaCount: 1

  service:
    type: ClusterIP

  #persistence:
  #  existingClaim: nfs-claim

phpmyadmin:
  enabled: true
  nameOverride: myadmin
  fullnameOverride: myadmin

  extraEnvVars:
    - name: LOG_LEVEL
      value: DEBUG