#To fix the issue CRD is too long
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator-crds
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: mariadb-operator
  project: default
  source:
    repoURL: https://github.com/mariadb-operator/mariadb-operator.git
    path: deploy/charts/mariadb-operator/crds/
    targetRevision: v0.0.19 #Must match Chart.yaml in "mariadb-operator" folder
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
